TRUTH = (
    "Bạn đã từng mê ai đó chưa?"
    "Bạn đã bao giờ đi qua cha mẹ của bạn làm 'điều đó'?",
    "Người cuối cùng bạn thích nhất là ai? Tại sao?",
    "Bạn đã bao giờ bị đình chỉ học chưa?",
    "Nếu bạn phải chọn giữa khỏa thân hoặc suy nghĩ của bạn xuất hiện trong một bong bóng suy nghĩ trên đầu để tất cả đọc, bạn sẽ chọn cái nào?",
    "Một điều bạn sợ mất là gì?",
    "Bạn có thích ai đó ngay bây giờ?",
    "Một điều về người bạn thân nhất của bạn khiến bạn ghen tị?",
    "Bạn sẽ lừa dối bạn trai của bạn để lấy một anh chàng giàu có?",
    "Bước ngoặt lớn nhất của bạn là gì?",
    "Lần cuối cùng bạn nói dối bố mẹ là khi nào và tại sao?",
    "Mô tả người bạn đời lý tưởng của bạn.",
    "Điều đáng sợ nhất mà bạn từng làm là gì?",
    "Apakah kamu pernah mengupil dan memakannya?",
    "Lần cuối cùng bạn nói dối bố mẹ là khi nào và tại sao?",
    "Bạn đã bao giờ nói dối tuổi của mình để tham gia một cuộc thi chưa?",
    "Bạn đã bao giờ bị bắt gặp đang kiểm tra ai đó chưa?",
)

DARE = (
    "Hiển thị những bức ảnh đáng xấu hổ nhất trên điện thoại của bạn"
    "Hiển thị năm người cuối cùng bạn đã nhắn tin và nội dung tin nhắn",
    "Cho phép cả nhóm gửi tin nhắn trực tiếp cho ai đó từ tài khoản Instagram của bạn",
    "Ăn tỏi sống",
    "Thực hiện 100 lần squat",
    "Giữ ba viên đá trong miệng của bạn cho đến khi nó tan chảy",
    "Nói điều gì đó bẩn thỉu với người bên trái bạn. Bạn có những người bạn!",
    "Mát-xa chân cho người bên phải bạn",
    "Cho 10 chất lỏng khác nhau có sẵn vào cốc và uống",
    "* Nói từ đầu tiên xuất hiện trong đầu bạn",
    "Cho một người mà bạn chọn",
    "Cởi bốn mảnh quần áo",
    "Thích 15 bài viết đầu tiên trên newsfeed Facebook của bạn",
    "Ăn một thìa mù tạt",
    "Nhắm mắt lại cho đến khi bạn rời đi",
    "Gửi sext cho người cuối cùng trong danh bạ của bạn",
    "Khoe khuôn mặt cực khoái của bạn",
    "Ăn chuối một cách quyến rũ",
    "Làm trống ví / ví của bạn và cho mọi người thấy có gì trong đó",
    "Cố gắng thu thập thông tin sexy nhất của bạn",
    "Giả vờ là người ở bên phải bạn trong 10 phút",
    "Ăn vặt mà không cần dùng tay",
    "Nói hai điều trung thực ​​về mọi người trong nhóm",
    "Twerk một lúc",
    "Cố gắng làm cho cả nhóm cười càng nhanh càng tốt",
    "Cố gắng đưa cả nắm tay vào miệng",
    "Kể cho mọi người nghe những câu chuyện đáng xấu hổ về bạn",
    "Thử liếm khuỷu tay của bạn",
    "Đăng ảnh tự sướng lâu đời nhất trên điện thoại của bạn trên Instagram Stories",
    "Kể câu chuyện buồn nhất mà bạn biết",
    "Tru như sói trong hai phút",
    "Nhảy không nhạc trong hai phút",
    "Múa cột với những chiếc cột tưởng tượng",
    "Để người khác cù bạn và cố gắng không cười",
    "Đưa đồ ăn nhẹ vào miệng cùng lúc nhiều nhất có thể",
    "Gửi ảnh tự chụp mới nhất của bạn.",
    "Gửi ảnh tự sướng xấu xí nhất của bạn.",
    "Gửi ảnh chụp màn hình lịch sử tìm kiếm trên facebook của bạn",
    "Gửi ảnh chụp màn hình thư viện của bạn.",
    "Gửi ảnh chụp màn hình hộp thư đến Messenger của bạn",
    "Nói điều gì đó rất thân mật.",
    "Gửi ảnh chụp màn hình hộp thư đến twitter của bạn",
    "Gửi ảnh chụp màn hình chính của bạn.",
    "Gửi một bản cover của bài hát yêu thích của bạn. ",
    "Làm một trò đùa có lời về một người nào đó và gửi bằng chứng.",
    "Thừa nhận người bạn thích hiện tại. ❤️",
    "Hãy nói cho tôi biết ai là tình yêu đích thực của bạn.",
    "Gửi ảnh chụp màn hình thư viện của bạn.",
    "Đặt ảnh của người ấy làm ảnh dp của bạn.",
    "Đề nghị tôi dũng cảm.",
)
